# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CapstoneProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for CapstoneProject
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    

  target 'CapstoneProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapstoneProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
