# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

  # Pods for CapstoneProject
pod "YelpAPI"


target 'CapstoneProject' do
    

  target 'CapstoneProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapstoneProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
